In [ ]:
'''
Introduction to Numpy
Numpy is a open source library that is used for the scientific computing in Python. 
It provides support for large, multi-dimensional arrays and matrices, 
along with a collection of mathematical functions to operate on these arrays efficiently.

matheatical functions like cos, sin, log, exp, etc. are available in numpy.

Difference between list and numpy array:
(1). List Hetrogeneous data type and Numpy is Homogeneous data type .
(2). List takes more memory as compare to Numpy .
(3) List takes more execution time as compare to Numpy .

'''

In [ ]:
# pip install numpy
# !pip install numpy
# uv add -r requirements. txt

# for vs code
# > for jupyter notebook
# --- > for uv in vs code .

In [2]:
a = [1,2,3,33,4]
type(a)

list

In [3]:
import numpy as np
b = np.array(a)
type(b)

numpy.ndarray

In [6]:
a = []
size = int(input('enter the size of the array'))
for i in range(size):
    num = int(input(''))
    a.append(num)
print(a)

[1, 55, 65, 35]


In [9]:
a = np.array(a)
print(type(a))

<class 'numpy.ndarray'>


In [13]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [14]:
''' 
this point is very impt -> if you understand this then half of the data science u will get 
cnn -> work on images ->images are made up of pixels -> pixel work in matrix format -> this is matrix
'''

' \nthis point is very impt -> if you understand this then half of the data science u will get \ncnn -> work on images ->images are made up of pixels -> pixel work in matrix format -> this is matrix\n'

In [11]:
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# matrix -> made up of rows   & columns
'''
 # row_1 -> [1,2,3]
  row_2 ->[4,5,6]
  row_3->[7,8,9]

  col_! ->[1,4,7]
  col_2 ->[2,5,8]
  col_3 ->[3,6,9]

# total element -> rows * cols -> 3 *3 -> 9
'''

In [16]:
print('shape of the matrix',b.shape)
print('total element in the matrix', b.size)

shape of the matrix (3, 3)
total element in the matrix 9


In [18]:
a = [[1,2,3,5],[4,5,6,7],[7,8,9,10]]
b = np.array(a)
print(b)

[[ 1  2  3  5]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [19]:
print('shape of the matrix',b.shape)
print('total element in the matrix', b.size)

shape of the matrix (3, 4)
total element in the matrix 12


In [20]:
# how to check the dimension of  the array

b.ndim

2

In [ ]:
a = np.array([[[1,2,3],[4,5,6]]])
a.ndim
# short trick to get check the dim-> check the total sq bracket will get the dim

3

In [ ]:
# why we are studing numpy
# images ---> pixels(0,255) --->matrix format -> operations
# Deep learning---> Artitifical Neurons -> will have some weights -> created by numpy
# Datasets -> if we are working on dataset and we want to 
# add colm with some of the random vaules -> vaules will be generated by numoy ->
# then values attach by pandas

In [ ]:
# Pre- defined function

# 1. zeros() -> will make everything zero 

# why we use zeros or story behind it:
# we have pixels (0-255) -> if anything i am seeing thing white the its pixel is 255 and for black  its 
# 0  -> when we normalize this means scale down krna  value will convert between 0 to 1

# 0 -> black , 1-> white

In [25]:
# zeros -> it will create an array with the values zeros in either 1D or multi dimension
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [33]:
a = np.zeros(((3,3,3)))
print(a)
a.ndim
# 3 dimension space

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


3

In [34]:
a = np.zeros((3,4))
print(a)
a.ndim

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2

In [ ]:
'''
Use in Image Processing

If I want to add a black shadow or a black-colored region to an image, 
I can use np.zeros() because zero values represent black pixels.
'''

In [ ]:
# 2. Ones() -> it will create an array with the values of 1 in either 1D or multi dim
a  = np.ones(3)
print(a)


[1. 1. 1.]


In [ ]:
# Creating White Color

# To create a white image or white patch, we can use np.ones() and multiply it by 255