In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
a = np.zeros(4)

In [8]:
a

array([0., 0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
# (3) Eye -> it will create an array diagnoal position element will be 1 and other will be zeros

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
'''
if rows  == columns -> symmetric matrix
else
rows != columns -> asymmetric matrix
 '''    

'\nif rows  == columns -> symmetric matrix\nelse\nrows != columns -> asymmetric matrix\n '

In [14]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
# (4) ->    it will create an array in which we can  set our  custom values at diagonal postion

In [17]:
a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [18]:
# (5) Random Module
# Randint() -> it will create an array randomly in a given range
# syntax -> np.random.randint(min_range,max_Range,total_number)


In [21]:
a = np.random.randint(1,5,2)
print(a)

[3 2]


In [ ]:
# (b).  rand() ---> it will generate a random number from 0 to 1
# syntax : np.random.rand(total_number)

In [22]:
np.random.rand(4)

array([0.0762831 , 0.20777993, 0.68512182, 0.75342983])

In [23]:
# (c)  seed() -->  it will fix or lock  our generated data
# syntax np.random.seed(45)
# a = np.random.randint(1,10,3)

In [32]:
np.random.seed(43)
a = np.random.randint(1,10,5)
print(a)

[5 1 2 6 1]


In [33]:
# view and copy

In [37]:
# view
a = np.array([10,20,30,40,50])
b = a[1:4]
b[1:4]

array([30, 40])

In [38]:
b[:] = 0
b

array([0, 0, 0])

In [39]:
a

array([10,  0,  0,  0, 50])

In [40]:
# copy

In [41]:
# view
a = np.array([10,20,30,40,50])
b = a[1:4].copy()
b[1:4]

array([30, 40])

In [42]:
b[:] = 0
b

array([0, 0, 0])

In [43]:
a

array([10, 20, 30, 40, 50])

In [44]:
# reshaping the array
# condition -> rows * columns  = total elements

In [46]:
a = np.random.randint(1,50,12)
a

array([35, 12,  3, 36,  5, 37, 49, 13, 25, 48, 33, 11], dtype=int32)

In [48]:
a = a.reshape(3,4)
a

array([[35, 12,  3, 36],
       [ 5, 37, 49, 13],
       [25, 48, 33, 11]], dtype=int32)

In [49]:
a.reshape(2,6)

array([[35, 12,  3, 36,  5, 37],
       [49, 13, 25, 48, 33, 11]], dtype=int32)

In [50]:
a.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [51]:
# y = mx +b
# m = matrix --> weights
# x = values  --> matrix

# matrix(column)  *matrix(row)

In [52]:
a.reshape(-1,3)

array([[35, 12,  3],
       [36,  5, 37],
       [49, 13, 25],
       [48, 33, 11]], dtype=int32)

In [54]:
a.reshape(2,-1)

array([[35, 12,  3, 36,  5, 37],
       [49, 13, 25, 48, 33, 11]], dtype=int32)

In [57]:
# operations on array
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [58]:
a*2

array([2, 4, 6, 8])

In [59]:
a = [1,2,3]*2
a

[1, 2, 3, 1, 2, 3]

In [60]:
a = np.arange(5,9)
a

array([5, 6, 7, 8])

In [68]:
b = np.random.randint(1,10,4)
b

array([5, 9, 8, 5], dtype=int32)

In [69]:
a = a.reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [70]:
b = b.reshape(2,2)
b


array([[5, 9],
       [8, 5]], dtype=int32)

In [71]:
a*b

array([[25, 54],
       [56, 40]])

In [72]:
a+b

array([[10, 15],
       [15, 13]])

In [73]:
a-b

array([[ 0, -3],
       [-1,  3]])

In [ ]:
a.dot(b)  #this is matrix multiplicatio

#  5*5 + 6*8 -> 73 
# same other are calulcated

array([[ 73,  75],
       [ 99, 103]])

In [76]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [80]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [81]:
b = a%2 ==0
b

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [82]:
b = a%2 != 0
b

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False])

In [83]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [84]:
a**2

array([ 1,  4,  9, 16])

In [85]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.sum(a)

np.int64(45)

In [88]:
np.sum(a,axis=1) # sum row wise when axis 

array([ 6, 15, 24])

In [ ]:
np.sum(a,axis = 0)

array([12, 15, 18])